import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import type { MediaProbe, TranscodeProgress } from '../../contracts/media.js';
import { ProcessRunnerError } from '../errors.js';
import { isFaststart, parseTopLevelBoxes } from '../mp4-boxes.js';
import {
  createNodeMediaPipeline,
  findFfmpeg,
  nodeFsAdapter,
  nodeProcessRunner,
} from '../node/index.js';
import { LineSplitter } from '../node/process-runner.js';
import { nodeSha256 } from '../node/sha256.js';
import { MemorySink } from '../testing/fakes.js';

/**
 * Real-binary tests. Resolved via `NUTFLIX_FFMPEG`, then /tmp/opencode/ffmpeg/, then PATH
 * (see FFMPEG-PIN.md). Skipped — not failed — when no binary is present, so `npm run ci` is
 * green either way. Test media is generated by ffmpeg itself (lavfi), never committed.
 */
const bins = findFfmpeg();
const ffmpegAvailable = bins !== undefined;

const decode = (b: Uint8Array): string => new TextDecoder().decode(b);

describe('nodeProcessRunner (no ffmpeg needed)', () => {
  const runner = nodeProcessRunner();

  it('captures exit code, stdout bytes and stderr lines split on \\r and \\n', async () => {
    const lines: string[] = [];
    const r = await runner.run(
      'sh',
      ['-c', 'printf "out"; printf "a\\rb\\nc\\r\\nd" >&2; exit 3'],
      {
        onStderrLine: (l) => {
          lines.push(l);
        },
      },
    );
    expect(r.exitCode).toBe(3);
    expect(decode(r.stdout)).toBe('out');
    expect(r.stderr).toBe('a\rb\nc\r\nd');
    expect(lines).toEqual(['a', 'b', 'c', 'd']);
  });

  it('passes argv verbatim — a hostile argument is never interpreted', async () => {
    const hostile = '$(touch /tmp/pwned); rm -rf / #\'"';
    const r = await runner.run('printf', ['%s', hostile]);
    expect(decode(r.stdout)).toBe(hostile);
  });

  it('rejects with ProcessRunnerError(spawn-failed, ENOENT) for a missing binary', async () => {
    const err = await runner
      .run('/definitely/not/here/ffmpeg', ['-version'])
      .catch((e: unknown) => e);
    expect(err).toBeInstanceOf(ProcessRunnerError);
    expect(err).toMatchObject({
      name: 'ProcessRunnerError',
      code: 'spawn-failed',
      errno: 'ENOENT',
      file: '/definitely/not/here/ffmpeg',
    });
  });

  it('honours an abort signal by killing the child', async () => {
    const ac = new AbortController();
    const p = runner.run('sleep', ['30'], { signal: ac.signal });
    setTimeout(() => {
      ac.abort();
    }, 50);
    await expect(p).rejects.toMatchObject({ code: 'aborted' });
    await expect(
      runner.run('sleep', ['30'], { signal: AbortSignal.abort() }),
    ).rejects.toMatchObject({ code: 'aborted' });
  });

  it('LineSplitter buffers partial lines across pushes', () => {
    const got: string[] = [];
    const s = new LineSplitter((l) => got.push(l));
    s.push('out_time_us=12');
    s.push('34\nfps=1');
    s.push('\r');
    s.flush();
    expect(got).toEqual(['out_time_us=1234', 'fps=1']);
  });
});

describe('nodeFsAdapter', () => {
  it('creates temp dirs under tmpDir, streams chunks of the requested size, stats and removes', async () => {
    const base = await mkdtemp(join(tmpdir(), 'nutflix-fsadapter-'));
    try {
      const fs = nodeFsAdapter({ tmpDir: base });
      const dir = await fs.mkdtemp('work-');
      expect(dir.startsWith(join(base, 'work-'))).toBe(true);
      const data = new Uint8Array(10_000).map((_, i) => i % 251);
      await fs.writeFile(join(dir, 'a.bin'), data);
      expect((await fs.stat(join(dir, 'a.bin'))).size).toBe(10_000);
      expect(await fs.readFile(join(dir, 'a.bin'))).toEqual(data);
      const sizes: number[] = [];
      for await (const c of fs.readChunks(join(dir, 'a.bin'), 4096)) sizes.push(c.length);
      expect(sizes).toEqual([4096, 4096, 1808]);
      await fs.rm(dir, { recursive: true });
      await expect(fs.stat(dir)).rejects.toThrow();
    } finally {
      await rm(base, { recursive: true, force: true });
    }
  });
});

describe.skipIf(!ffmpegAvailable)('real ffmpeg end-to-end', () => {
  let base = '';
  let input = '';
  const runner = nodeProcessRunner();

  beforeAll(async () => {
    base = await mkdtemp(join(tmpdir(), 'nutflix-l8-'));
    // Hostile input name: spaces, shell metacharacters, quotes. Generated by ffmpeg itself.
    input = join(base, 'src $(id); rm -rf ~ \'a\' "b" #.mp4');
    const gen = await runner.run(bins!.ffmpeg, [
      '-hide_banner',
      '-nostdin',
      '-y',
      '-loglevel',
      'error',
      '-f',
      'lavfi',
      '-i',
      'testsrc=size=1280x720:rate=30:duration=4.5',
      '-f',
      'lavfi',
      '-i',
      'sine=frequency=440:duration=4.5',
      '-c:v',
      'libx264',
      '-preset',
      'ultrafast',
      '-pix_fmt',
      'yuv420p',
      '-c:a',
      'aac',
      '-shortest',
      input,
    ]);
    expect(gen.exitCode, gen.stderr).toBe(0);
  }, 60_000);

  afterAll(async () => {
    if (base) await rm(base, { recursive: true, force: true });
  });

  it('probes the generated clip (ffprobe JSON → MediaProbe), source is NOT faststart', async () => {
    const p = createNodeMediaPipeline({ binaries: bins!, tmpDir: base });
    const probe = await p.probe(input);
    expect(probe.container).toBe('mov,mp4,m4a,3gp,3g2,mj2');
    expect(probe.durationSec).toBeCloseTo(4.5, 1);
    expect(probe.video).toMatchObject({
      codec: 'h264',
      width: 1280,
      height: 720,
      fps: 30,
      pixelFormat: 'yuv420p',
    });
    expect(probe.audio).toMatchObject({ codec: 'aac', channels: 1, sampleRate: 44100 });
    // ffmpeg's default mp4 muxer writes moov LAST — our box scanner must say so.
    expect(probe.faststart).toBe(false);
  });

  it('transcodes the ladder: faststart verified by box order, sha256, dims, aligned keyframes, thumbs, placeholder, storyboard', async () => {
    const p = createNodeMediaPipeline({ binaries: bins!, tmpDir: base, preset: 'ultrafast' });
    const probe = await p.probe(input);
    const plan = p.plan(probe);
    expect(plan.renditions.map((r) => r.label)).toEqual(['720p', '360p']);
    const progress: TranscodeProgress[] = [];
    const out = await p.transcode(input, plan, (e) => progress.push(e));

    for (const r of out.renditions) {
      const bytes = await readFile(r.path);
      // Independent verification: parse the top-level boxes of the real file.
      const boxes = parseTopLevelBoxes(new Uint8Array(bytes));
      expect(boxes.map((b) => b.type)).toEqual(['ftyp', 'moov', 'free', 'mdat']);
      expect(isFaststart(boxes)).toBe(true);
      expect(r.faststart).toBe(true);
      expect(r.size).toBe(bytes.length);
      const h = nodeSha256();
      h.update(new Uint8Array(bytes));
      expect(r.sha256).toBe(h.digest());
      expect(r.sha256).toMatch(/^[0-9a-f]{64}$/);
      const [w, hgt] = r.spec.label === '720p' ? [1280, 720] : [640, 360];
      expect([r.width, r.height]).toEqual([w, hgt]);
      // Keyframes every GOP_SECONDS (2 s) on every rendition → aligned for switching.
      const kf = await runner.run(bins!.ffprobe, [
        '-v',
        'error',
        '-skip_frame',
        'nokey',
        '-select_streams',
        'v:0',
        '-show_entries',
        'frame=pts_time',
        '-of',
        'csv=p=0',
        r.path,
      ]);
      expect(kf.exitCode).toBe(0);
      const times = decode(kf.stdout)
        .split(/\r?\n/)
        .filter((l) => l.trim() !== '')
        .map((l) => Number(l.replace(/,$/, '')));
      expect(times.map((t) => Math.round(t * 100) / 100)).toEqual([0, 2, 4]);
    }

    // rendition progress from `-progress pipe:2` reached 100 (fps is only reported for
    // encodes long enough for ffmpeg to measure one, so it is not asserted here)
    const last720 = progress.filter((e) => e.stage === 'rendition' && e.label === '720p').at(-1);
    expect(last720).toMatchObject({ percent: 100 });
    const pct = progress
      .filter(
        (e): e is Extract<TranscodeProgress, { stage: 'rendition' }> => e.stage === 'rendition',
      )
      .filter((e) => e.label === '360p')
      .map((e) => e.percent);
    expect(pct[0]).toBe(0);
    expect(pct.at(-1)).toBe(100);
    expect([...pct].sort((a, b) => a - b)).toEqual(pct);

    // thumbnails: real JPEGs (SOI marker), hashed
    expect(out.thumbnails).toHaveLength(4);
    for (const t of out.thumbnails) {
      const b = await readFile(t.path);
      expect([b[0], b[1]]).toEqual([0xff, 0xd8]);
      const h = nodeSha256();
      h.update(new Uint8Array(b));
      expect(t.sha256).toBe(h.digest());
    }
    // placeholder: a real, tiny inline JPEG
    expect(out.placeholderDataUrl.startsWith('data:image/jpeg;base64,/9j/')).toBe(true);
    expect(out.placeholderDataUrl.length).toBeLessThan(2000);

    // storyboard: 4.5 s at 1 s → 5 tiles in one row, 160 px wide each → 800 px sprite
    expect(out.storyboard).toMatchObject({ cols: 5, rows: 1, intervalSec: 1 });
    const sb = await readFile(out.storyboard!.path);
    expect([sb[0], sb[1]]).toEqual([0xff, 0xd8]);
    const vtt = await readFile(out.storyboard!.vttPath, 'utf8');
    expect(vtt).toContain('storyboard.jpg#xywh=0,0,160,90');
    expect(vtt).toContain('storyboard.jpg#xywh=640,0,160,90');
    expect(vtt).toContain('00:00:04.000 --> 00:00:04.500');

    // publish: stream into a sink, sha256 re-verified
    const sink = new MemorySink();
    const pub = await p.publish(out.renditions[1]!, sink);
    expect(pub.size).toBe(out.renditions[1]!.size);
    expect(pub.sha256).toBe(out.renditions[1]!.sha256);
    expect(sink.puts[0]?.bytes.length).toBe(pub.size);
    expect(pub.hyper.blob.blockLength).toBe(Math.ceil(pub.size / 65_536));
  }, 120_000);

  it('does not upscale: a 240p source yields one native rendition', async () => {
    const small = join(base, 'small.mp4');
    const gen = await runner.run(bins!.ffmpeg, [
      '-hide_banner',
      '-nostdin',
      '-y',
      '-loglevel',
      'error',
      '-f',
      'lavfi',
      '-i',
      'testsrc=size=320x240:rate=25:duration=1',
      '-c:v',
      'libx264',
      '-preset',
      'ultrafast',
      '-pix_fmt',
      'yuv420p',
      small,
    ]);
    expect(gen.exitCode, gen.stderr).toBe(0);
    const p = createNodeMediaPipeline({ binaries: bins!, tmpDir: base, preset: 'ultrafast' });
    const probe: MediaProbe = await p.probe(small);
    expect(probe.audio).toBeUndefined();
    const plan = p.plan(probe);
    expect(plan.renditions.map((r) => r.label)).toEqual(['240p']);
    const out = await p.transcode(small, plan, () => undefined);
    expect([out.renditions[0]?.width, out.renditions[0]?.height]).toEqual([320, 240]);
    expect(out.renditions[0]?.faststart).toBe(true);
  }, 60_000);

  it('a broken input fails with process-failed and ffmpeg stderr attached', async () => {
    const junk = join(base, 'junk.mp4');
    await nodeFsAdapter().writeFile(junk, new TextEncoder().encode('this is not a video'));
    const p = createNodeMediaPipeline({ binaries: bins!, tmpDir: base });
    await expect(p.probe(junk)).rejects.toMatchObject({
      name: 'MediaError',
      code: 'process-failed',
    });
  });
});
